services:
  # ---------- PostgreSQL ----------
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: rag_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ---------- 向量嵌入批次 ----------
  embed:
    build:
      context: .
      dockerfile: docker/Dockerfile.embed
    volumes:
      - ./data:/code/data        # 把向量庫存回本機
    depends_on:
      - db

  # ---------- FastAPI ----------
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api

    # 先載入 .env（LINE token、OpenAI key…）
    env_file: .env

    # 其餘在 compose 內覆寫 / 補充
    environment:
      # ★ 連線到容器內的 db，而不是 localhost
      DATABASE_URL: >-
        postgresql+psycopg2://rag_user:rag_pass@db:5432/rag_db

      # ngrok token 也可以留在 .env，這裡示範直接吃 shell 的變數
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

    volumes:
      - ./data:/code/data        # 讀向量庫
      - ./models:/code/models    # 讀 TinyLlama gguf
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
