name: CI

on: [push]     # 或改成 workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke test
        run: |
          python - <<'PY'
          from crawler.fetcher import crawl
          print("✅ crawler ok, fetched 0 papers (dry run)")
          PY
