name: CI

on:
  push:            # main 分支推送就跑
    branches: [main]
  pull_request:    # PR 也跑一次確認
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 預裝系統 Python 就好，venv 由腳本自己建
      - name: Run smoke test
        run: bash bin/smoke_test.sh
